server:
  port: 8080
spring:
  jackson:
    date-format: ru.asteises.storageapi.invoker.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres #???? ? ???? ?????? CHANGE BASENAME (neftlink or postgres)
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver #??????? ??? ?????? ???????? ?? ???????????? ? ???? ??????
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    enabled: true
    change-log: 'classpath:liquibase/changelog-master.yml'

logging:
  level:
    root: warn #??????? ??????????????
    ru: debug  #???????? ???? ??????????
